version: '3'
services:
  zookeeper:
    image: library/zookeeper:3.5
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: solsson/kafka:2.2.0
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    entrypoint: ./bin/kafka-server-start.sh ./config/server.properties --override zookeeper.connect=zookeeper:2181 --override advertised.listeners=PLAINTEXT://localhost:9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
